//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Appeals struct {
	ID           int32 `sql:"primary_key"`
	UserID       int32
	AppealTypeID int32
	Title        string
	Description  string
	Address      string
	Latitude     float64
	Longitude    float64
	StatusID     int32
}
