//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Tko struct {
	ID        int32 `sql:"primary_key"`
	Address   *string
	Latitude  *float64
	Longitude *float64
	Type      *string
}
