version: '3.9'

x-common-variables: &database-credentials
  POSTGRES_DB: urbathon
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: 123456
  POSTGRES_HOST: db
  POSTGRES_PORT: 5432

services:
  cache:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server
    environment:
      - REDIS_PORT=6379

  database:
    image: postgres:latest
    container_name: db
    environment:
      <<: *database-credentials
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

  webapi:
    image: webapi
    build: ../
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    environment:
      <<: *database-credentials
    command: ./urbathon-backend-2023 -srvAddr=webapi -srvPort=8080