version: '3.9'

services:
  database:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_DB=hackathon
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10


  webapi:
    image: webapi
    build: ../
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    command: ./urbathon-backend-2023 -dbAddr=db -dbUser=postgres -dbPass=123456 -dbName=hackathon -dbPort=5432 -srvAddr=webapi -srvPort=8080