//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	AppealCategories = AppealCategories.FromSchema(schema)
	AppealCommentPhotos = AppealCommentPhotos.FromSchema(schema)
	AppealComments = AppealComments.FromSchema(schema)
	AppealPhotos = AppealPhotos.FromSchema(schema)
	AppealStatus = AppealStatus.FromSchema(schema)
	AppealTypes = AppealTypes.FromSchema(schema)
	Appeals = Appeals.FromSchema(schema)
	News = News.FromSchema(schema)
	NewsCategories = NewsCategories.FromSchema(schema)
	NewsPolls = NewsPolls.FromSchema(schema)
	OrganizationAppealCategory = OrganizationAppealCategory.FromSchema(schema)
	Organizations = Organizations.FromSchema(schema)
	PollOptions = PollOptions.FromSchema(schema)
	SchemaMigrations = SchemaMigrations.FromSchema(schema)
	UserPollVotes = UserPollVotes.FromSchema(schema)
	UserRoles = UserRoles.FromSchema(schema)
	Users = Users.FromSchema(schema)
}
