definitions:
  input.User:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  input.UserLogin:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  response.User:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: login
      parameters:
      - description: login and password
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/input.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.User'
      summary: login
  /auth/logout:
    post:
      consumes:
      - application/json
      description: logout
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: logout
  /auth/register:
    post:
      consumes:
      - application/json
      description: register
      parameters:
      - description: User
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/input.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.User'
      summary: register
  /auth/test:
    post:
      consumes:
      - application/json
      description: auth test
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.User'
      summary: auth test
swagger: "2.0"
